# Generated by Django 2.0 on 2017-12-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strength2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutdataform',
            old_name='workout_id',
            new_name='exersise',
        ),
        migrations.AddField(
            model_name='workoutdataform',
            name='clicked',
            field=models.BooleanField(default=True),
        ),
    ]
