# Generated by Django 2.0 on 2018-01-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strength2', '0003_auto_20171218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutdataform',
            name='userName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='strength2.UserDataForm'),
            preserve_default=False,
        ),
    ]
